name: test_project  
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:  
test_project:  
   runs-on: ubuntu-latest  
   steps:  
     - uses: actions/checkout@v2  
     - uses: actions/setup-python@v2  
     - run: pip install -r requirements.txt  # install requirements to enable GitHub run our code
     - run: pytest . # run the unit test  
